[http.middlewares]
[http.middlewares.my-ldapAuth.plugin.ldapAuth]
Enabled = "true"
LogLevel = "DEBUG"
Attribute = "uid"
BaseDN = "dc=example,dc=com"
AllowedGroups = [
    "ou=mathematicians,dc=example,dc=com",
    "ou=italians,ou=scientists,dc=example,dc=com",
]
AllowedUsers = ["euler", "uid=euclid,dc=example,dc=com"]
# SearchFilter must escape curly braces when using toml file
# https://toml.io/en/v1.0.0#string
# SearchFilter = '''(\{\{.Attribute\}\}=\{\{.Username\}\})'''
[[http.middlewares.my-ldapAuth.plugin.ldapAuth.ServerList]]
Url = "ldaps://ldap2.forumsys.com"
Port = "636"
Weight = 10
[[http.middlewares.my-ldapAuth.plugin.ldapAuth.ServerList]]
Url = "ldap://ldap.forumsys.com"
Port = "389"
Weight = 5
